<?php

namespace Database\Seeders;

use App\Models\Cafe;
use App\Models\Category;
use Illuminate\Database\Seeder;

class CafeSeeder extends Seeder
{
    public function run(): void
    {
        $cafes = [
            [
                'name'       => 'Nyctophily Coffee',
                'address'    => 'Jl. Tembalang Sel. IV No.2, Pedalangan, Kec. Banyumanik, Jawa Tengah',
                'phone'      => '081575441803',
                'price_range'=> 'Murah',
                'open_hours' => '9.00 am–10.00 pm',
                'sosmed'     => 'instagram.com/nyctophilycoffee',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGCKCNWlmm7IpTJZDHtIdhs2eSLhsFRXPqmyQw1SH1MtBNg5ckyqn6QPj4P7eBS9TSdb3Cjp41DDNTWxaufJLXNSlgr4s1txy_2nerCLZVx_5da_OuyzZQ3eahtjLXjb88bw2BOJg=w426-h240-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Mitsu Cafe',
                'address'    => 'Jl. KH. Sirojudin No.30, RT.5/RW.3, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275',
                'phone'      => '085640282121',
                'price_range'=> 'Murah',
                'open_hours' => '12.00–10.30 pm',
                'sosmed'     => '',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAENHkSHQMyBoWK-qhdS-805cB_JgxLovMqTMAhPD-y0uJ0crs4vVpPW3o7mxZclSPpzc9J3AH2V-1rHojT9QK6b-msxkaZ1Es2jrjc9FYyd1jZ5WmNmRKwqTND36KBBZLz4VIQ=w408-h544-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Lingkar Coffee & Idea',
                'address'    => 'Jln. K.H. Sirojudin No. 5, Tembalang, Semarang, Jawa Tengah',
                'phone'      => '062811711135',
                'price_range'=> 'Sedang',
                'open_hours' => '8.00 am–12.00 am',
                'sosmed'     => 'https://www.instagram.com/lingkarcoffee',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGKqnSBe-msKo7njHvv30lG4KdPvkpTSTbDWVumqOIZGkyvZG70gwtXKk5prLZNNczAqdRlStgG0Se84XiN06pRSvrXpmglqc479Jw5r51iZlAwmy7KTlIzmeZkhdmDTweUvIAj=w408-h612-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
            [
                'name'       => 'Kopi Nako',
                'address'    => 'Jalan Ngesrep Timur V, Sumurboto, Kecamatan Banyumanik, Kota Semarang, Jawa Tengah 50269',
                'phone'      => '085218814072',
                'price_range'=> 'Sedang',
                'open_hours' => '11.00 am–12.00 am',
                'sosmed'     => '@kopinako.semarang',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAHPnUaWsL1ou1LEobMbz43Gdn_XBItPl-872pp7IQ2zne5h8ums-FhAy7itblhtQKCKQIF-2W5r3aEbtVdillb6Bba9SVLBeumnrdNAaw9ucVF0_TfUJ0brqsCDR-jamGl6wHJ3l6vS50In=w408-h306-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
            [
                'name'       => 'Anantari Coffee',
                'address'    => 'Jalan Jangli Gabeng, Jangli, Kecamatan Tembalang, Kota Semarang, Jawa Tengah 50274',
                'phone'      => '082135759015',
                'price_range'=> 'Mahal',
                'open_hours' => '10.00 am–11.00 pm',
                'sosmed'     => '@anantari.smg',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGipbSGSr1PWlBqs16cL9YxY_4qwNlT1PLv8jtXq9rFnBiM1V9oS1inp0G-hxajzahVW0VVTmD8O6kaWjQ8M5KzLd-GDg9wMSAzZi3A7cV1HaYBpinHkZrn8QLkd1_oiYzfhGHyfxSXUL2J=w408-h544-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
            [
                'name'       => 'Peacock Coffie',
                'address'    => 'Jl. Gombel Lama No.11, Tinjomoyo, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50262',
                'phone'      => '',
                'price_range'=> 'Mahal',
                'open_hours' => 'Open 24 hours',
                'sosmed'     => '',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAFK9vN5x5APuE-AuSzg3baD7o3yJZULcaGnhGuL3hNNkHOJws8aC0BcuLLGAC9NJwi_zd0n6z5WVKpdi1Ow455tR7QbZ7KacDJsSRh1kC89UZvqahdyH0pmePYLLSCuWwqgPaTBETziIca5=w408-h544-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Kopi Tembalang',
                'address'    => 'Jalan Banjarsari Raya Tembalang No.53, Tembalang, Kecamatan Tembalang, Kota Semarang, Jawa Tengah 50275',
                'phone'      => '081328821881',
                'price_range'=> 'Murah',
                'open_hours' => '9.00 am–10.00 pm',
                'sosmed'     => '@kopitembalang',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAEfjrTE8oaZpkt2BH77p2t2SsgyX8VIuL0XloFs39f5AayDgRc6mCSoqhN-AiIstt56NmKdQsP2zQAtkokooLw5N4RtCFRlLBmhnTUhJRTzDDNI_BvVlytBQaSS9udT0EwxzEU4LA=w408-h509-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
            [
                'name'       => 'Bloomery Patisserie',
                'address'    => 'Jl. Ngesrep Tim. V Ruko No.22, Sumurboto, Banyumanik, Semarang City, Central Java 50268',
                'phone'      => '082122866426',
                'price_range'=> 'Mahal',
                'open_hours' => '9.00 am–10.00 pm',
                'sosmed'     => 'https://www.instagram.com/bloomerypatisserie',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAEpKgIK7Av6g-xmyTdv06sZ0eaNYKb0QZ_UJfwnavHKZnY_CmIeoraPNe9f8FDAZXk_sxwlZ0NWtp0OFHU4LX3xnAFrMvN2MHopWXWroXthu-WLtT_uDQigtZZzNVjdfJA9lDpQOTm-Joo=w408-h544-k-no',
                'category'   => 'Cafe Kue',
            ],
            [
                'name'       => 'hèr',
                'address'    => 'Jln. Banjarsari Selatan No. 47, Semarang, Indonesia 50275',
                'phone'      => '',
                'price_range'=> 'Mahal',
                'open_hours' => '10.00 am–9.00 pm',
                'sosmed'     => 'https://www.instagram.com/her.tdm',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAH2oveniiRXoOKnsHcCnlYhkjLNu-fzJ0FWWTKTxVZz9u1BrOeCG4wPVW2tO1LnJB-HbDDU0YjaSS6MKBOkhGV3AY_KyBGP46UZttk2ScBRhIZIfbjh8UN6RI5p3ahN3rsQ6wR1qGhb3lKi=w426-h240-k-no',
                'category'   => 'Cafe Kue',
            ],
            [
                'name'       => 'Semasa Kopi',
                'address'    => 'Jl. Mulawarman Raya No.4, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268',
                'phone'      => '089563491111',
                'price_range'=> 'Murah',
                'open_hours' => '9.00 am–12.00 am',
                'sosmed'     => '@semasa.kopi',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAFUgRvqlYyb3Ow03jkriapthdtg9Ec0C4wbAT6EmxGkvfPxNWhoM_Y2nEhAydYoRKxm7eEdRfT9VqzOvCJnGkoDKYFYLdzXVIPbFLmgQgXHFy2X53PyHkcyQGM4hSCqe0TrnsuD=w426-h240-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Ejaan Koffie',
                'address'    => 'Jalan. Banjarsari Selatan No.48B, Pedalangan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268',
                'phone'      => '085727084014',
                'price_range'=> 'Sedang',
                'open_hours' => 'Open 24 hours',
                'sosmed'     => '@ejaankoffie',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGeeepBjziQX7__-FajI-mRxEOB0aPAF49tYHp-LTypZLgxtu86P57v7pSJvoxqi-pQOMpGpZNzlFzOjKJTagGoF77nmdEynrMhF82RNScLpPAQ0Oejoa3AGZGpTFwRZ6h9fQhBxg=w408-h306-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'La Saveur Bakeshop',
                'address'    => 'Jl. Iwenisari No.20, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275',
                'phone'      => '082146046818',
                'price_range'=> 'Mahal',
                'open_hours' => '9.00 am–10.00 pm',
                'sosmed'     => 'https://www.instagram.com/lasaveur.id',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAEl0svSyGjhc2_1Avpe4SL5l-WKtQW2NbQPVl2q1J3W1rsiDqHdYyKryvvLn554YowSKpKnU1chLrUvU-d8LMF9ImA9e7TA8eA9FiPFFGqMyFqZH3jJSPLs4hgKfz6FW__JI5PNsnsDES0=w408-h612-k-no',
                'category'   => 'Cafe Kue',
            ],
            [
                'name'       => 'Kedai Kue Mommy',
                'address'    => 'Jl. Mulawarman II No.18B, Padangsari, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50267',
                'phone'      => '088215635909',
                'price_range'=> 'Murah',
                'open_hours' => '3.00–9.00 pm',
                'sosmed'     => 'https://www.instagram.com/kedaikue.mommy',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAEquWIrvO-_eIN4GrY7epF9xiDAv-dF5stjS18XRGOlCgvQXdxG4l_wrP2MB1BuxOx7ToaQHy2Rhx2q8z_qddZiKnMw57Ya7fVlDMfJZFKWkZVT_-m8JoCfMIcfh0t5Dhmfo6izxaFzRToL=w408-h306-k-no',
                'category'   => 'Cafe Kue',
            ],
            [
                'name'       => 'The Ambaru Coffee',
                'address'    => 'Jl. Mangunharjo, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276',
                'phone'      => '08112948882',
                'price_range'=> 'Mahal',
                'open_hours' => '9.00 am–11.00 pm',
                'sosmed'     => 'https://www.instagram.com/theambarucoffee',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGoi9HYWcQrIDGHkazDf_J1601tBS9Ey6Rod4atnBKexD7-BXcZqKxWNV879Dhy9z3K4Wosd-vXxNOklzG7SQ4CoXFwREwZD0EhoB93nxCJsDjC9Dff72pTEoIKIE9dmzx_Vcnhq-sE2Ldh=w408-h306-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
            [
                'name'       => 'Kopi Kemenangan',
                'address'    => 'Jl. Banyu Putih Raya, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah',
                'phone'      => '',
                'price_range'=> 'Murah',
                'open_hours' => '7.00 am–10.30 pm',
                'sosmed'     => 'kopikemenangan.id',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAHwVAe-G-rviJoU1Q2U5sbh4GCeSGYF1Ufb-U9HkP_psUeeiSq0EAaGaAeWHo186RMOMiexrFmXoQikT4g_woVrFpmiD-MxG-4mKI_ikTjLALfH3gv95S8ApqOJVCzvdwMSjzupl6qQbusl=w408-h725-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Anak Panah Kopi DipoHub',
                'address'    => 'Tembalang, Semarang City, Central Java 50275',
                'phone'      => '',
                'price_range'=> 'Mahal',
                'open_hours' => '7.00 am–12.00 am',
                'sosmed'     => 'https://www.instagram.com/dipohub.undip',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAHw2h_cBKzTVRGNcHjgAC0V-wej3RGNZqrLHW_Y85bcBH9czna7xZqtGzOL1ATQikGVXd9NuMfObDd2-7V_k6zgTghHM8fIUgvsuQIHYRcQVXZnbtkoOcoXR7rLdomWjIlHJoes=w408-h544-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
            [
                'name'       => 'Matera',
                'address'    => 'Jl. Banjarsari Selatan No.88, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268',
                'phone'      => '082135171266',
                'price_range'=> 'Sedang',
                'open_hours' => '11.00 am–11.00 pm',
                'sosmed'     => 'https://www.instagram.com/materacoffee',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAE9nj4-OGWPdKxqmQW_HmO2gUKZrW0y9LDQzf0ixRKFdO3IgLCxumhTZBddz0FrzffOXR3YJAW8vcUm1VDO8lsLDYwK8kAicLlKLx2vk03Aqv7eSukdb6LLZO7iHFuSQ2EmXkiT=w426-h240-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Palette Coffee',
                'address'    => 'Jl. Banjarsari Barat No.10, RT.07/RW.III, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50275',
                'phone'      => '082220029293',
                'price_range'=> 'Sedang',
                'open_hours' => '9.00 am–1.00 am',
                'sosmed'     => 'https://www.instagram.com/palettespace__',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAG_F2ZktXQ4Vk9QBCHy-ZE9RhRSEwbIOD_lPlM84rDYgFePRhzYNEvLyW0LZTVcfQFA1pBbXMaGpve3l6w8YTTKpleE4k9AA1MxP7a41QA0mH930ry4WRiMztaNWIJ0LybxOjpk=w408-h306-k-no',
                'category'   => 'Cafe WFC',
            ],
            [
                'name'       => 'Darabiru',
                'address'    => 'Jl. Mulawarman II No.28, Padangsari, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50264',
                'phone'      => '062895630303',
                'price_range'=> 'Sedang',
                'open_hours' => '10.00 am–10.00 pm',
                'sosmed'     => 'https://www.instagram.com/darabiru.coffee',
                'photo'      => 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAG844kMZ6oPPTQSUYd6XWlCCpfAq9s67SIGYRxRlBds8fmMgEmsBDTyD0d7wLDOJ0WFu77FbJnrhHGTLc0nICIVI8Od9kTExNR8GphsdaqbXjnWUh_h3JQ7GMErso0b5GV7SAU7w6eE0gGu=w408-h544-k-no',
                'category'   => 'Cafe Nongkrong',
            ],
        ];

        foreach ($cafes as $data) {
            $category = Category::firstOrCreate(['name' => $data['category']]);
            $cafe = Cafe::create([
                'name'        => $data['name'],
                'address'     => $data['address'],
                'phone'       => $data['phone'],
                'price_range' => $data['price_range'],
                'open_hours'  => $data['open_hours'],
                'sosmed'      => $data['sosmed'],
                'photo'       => $data['photo'],
            ]);
            $cafe->categories()->attach($category->id);
        }
    }
}